alertmanager:
  enabled: true
  ingress:
    enabled: false
 
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: zfs-iscsi-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi

grafana:
  enabled: true
 
  grafana.ini:
    server:
      root_url: https://grafana.terri.cc/
    auth.generic_oauth:
      name: Authentik
      enabled: true
      auto_login: false
      allow_sign_up: true
      scopes: openid,email,profile
      
      auth_url: https://auth.terri.cc/application/o/authorize/
      token_url: https://auth.terri.cc/application/o/token/
      api_url: https://auth.terri.cc/application/o/userinfo/
      
      client_id: ""
      client_secret: ""

      role_attribute_path: "'Viewer'"
      skip_org_role_sync: false
    security:
      disable_initial_admin_creation: true

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.terri.cc
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - hosts:
          - grafana.terri.cc
        secretName: grafana-terri-cc-tls
  
  assertNoLeakedSecrets: false

prometheus:
  enabled: true
  ingress:
    enabled: false

  prometheusSpec:
    retention: 14d    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: zfs-iscsi-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
